name: Manual Release

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: echo "Manual release workflow is working!"
